trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# 1. Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# 2. Install and build React frontend (vite)
- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Build React frontend'

# 3. Install backend dependencies
- script: |
    cd backend
    npm install
  displayName: 'Install backend dependencies'

# 4. Inject environment variables into .env file
- script: |
    cd backend
    echo "PORT=$(PORT)" >> .env
    echo "MONGODB_URI=$(MONGODB_URI)" >> .env
  displayName: 'Create .env file for backend'

# 5. (Optional) Run server or deploy
# You could run your server here, or deploy to Azure App Service.
